#' Generate a Feather file from data in a Seurat object.
#'
#' This function retrieves data in specified slots ("metadata", "assays", or "reductions") from a user-inputted Seurat object and writes that data to a Feather file. The first column of data contains cell barcodes from a CITE-seq experiment, and subsequent columns contain metadata or count data for various assays (counts for each ADT, gene, etc.) and reductions (embeddings for UMAPs, PCAs, etc.). This columnar data storage format allows for much faster read access in downstream app processes.
#' 
#' @param assay_or_reduction_name A string specifying the name of an assay (e.g., ADT, RNA, etc.) or reduction (e.g., PCA, UMAP, etc.) present in the Seurat object that is passed as a parameter to this function.
#' @param seurat_object A Seurat object containing metadata, assays, and reductions for a CITE-seq experiment.
#' @param slot_name A string specifying one of three possible values: "metadata", "assays", or "reductions".
#' @param output_dir_path A string specifying the relative path to an output directory in which to store the Feather file generated by this function. Feather files generated from the same input Seurat object should be stored in the same directory. Path is relative to the current working directory.
#' @param feather_file_prefix A string specifying the prefix for each Feather file generated from an input Seurat object.
#'
#' @importFrom arrow write_feather
#' @importFrom SeuratObject GetAssayData Embeddings
#' @importFrom tibble rownames_to_column
#' 
#' @return The relative path to the feather file that was generated. This value is returned invisibly.
#' @export
#'
#' @examples \dontrun{
#' myso <- readRDS("path/to/RDS_file.rds")
#' write_seurat_to_feather(seurat_object = myso, slot_name = "metadata", feather_parent_dir = "citeviz_arrow", feather_file_prefix = "project123")
#' }
write_seurat_to_feather <- function(assay_or_reduction_name = NULL, seurat_object, slot_name, output_dir_path, feather_file_prefix){
  # initialize output_file_identifier to empty string by default
  output_file_identifier <- ""
  
  if (slot_name == "metadata"){
    subdata_df <- as.data.frame(seurat_object[[]]) 
  }
  if (slot_name == "assays"){
    # transpose assay data so that that rownames are cell barcodes and column names are ADTs/Genes/etc.
    # convert transposed output matrix into data frame again
    subdata_df <- as.data.frame(SeuratObject::GetAssayData(seurat_object, 
                                                           slot = "data", 
                                                           assay = assay_or_reduction_name)) %>% 
      t() %>%
      as.data.frame()
    output_file_identifier <- paste0("_", assay_or_reduction_name)
  }
  else if (slot_name == "reductions"){
    subdata_df <- as.data.frame(SeuratObject::Embeddings(seurat_object, reduction = assay_or_reduction_name)) 
    output_file_identifier <- paste0("_", assay_or_reduction_name)
  }
  
  # convert rownames of dataframe to a column in the dataframe because for some reason, writing to a feather file doesn't preserve the original rowname data
  subdata_df <- subdata_df %>% tibble::rownames_to_column("cell_barcodes")
  
  # generate platform-independent output file path
  output_filepath <- file.path(output_dir_path,
                               paste0(feather_file_prefix, "_", slot_name, output_file_identifier, ".feather"))
  
  # check if output directory exists in user's filesystem. If not, create the necessary folders in the path
  if (!dir.exists(output_dir_path)) {
    dir.create(output_dir_path)
  }
  
  # write extracted subdata to output file
  arrow::write_feather(x = subdata_df, sink = output_filepath)
  
  return(invisible(output_filepath))
}


#' Generate Feather files from data in a Seurat object.
#' 
#' This function is called before running the app so that the user's Seurat object can be converted into Feather files.
#'
#' @param seurat_object A Seurat object containing metadata, assays, and reductions for a CITE-seq experiment.
#' @param feather_parent_dir A string specifying the directory in which all project-specific Feather folders/files are stored for this app. Do not include slashes. Default value is a folder named "citeviz_arrow" in the current working directory.
#' @param feather_file_prefix A string specifying the prefix for each feather file generated from an input Seurat object. These Feather files will be stored in a sub-directory named with the same prefix, and this subfolder can be found within the feather parent directory. It is recommended to set the feather file prefix to be the same as the base filename of the original RDS file the Seurat object originated from (i.e., if the input Seurat object came from an RDS file called "my_project_data.rds", then the prefix for the arrow files should be "my_project_data".) 
#'
#' @importFrom SeuratObject Assays Reductions
#'
#' @return The path to the sub-directory (in the format "feather_parent_dir/feather_file_prefix") where Feather files generated from the same input Seurat object are stored. This path is relative to the user's current working directory. This value is returned invisibly.
#' @export
#'
#' @examples \dontrun{
#' myso <- readRDS("path/to/RDS_file.rds")
#' create_feather_files(seurat_object = myso, feather_parent_dir = "citeviz_arrow", feather_file_prefix = "project123")
#' }
create_feather_files <- function(seurat_object, feather_parent_dir = "citeviz_arrow", feather_file_prefix = "project1") {
  # generate a file prefix for the feather files to be generated, so that 
  # they don't overwrite existing feather files generated from other RDS files
  # if (is.null(feather_file_prefix)) {
  #   feather_file_prefix <- tools::file_path_sans_ext(basename(rds_filepath))
  # }
  
  # generate platform-independent output folder path
  output_dir_path <- file.path(feather_parent_dir, feather_file_prefix)
  
  # create feather file for metadata
  write_seurat_to_feather(seurat_object = seurat_object, 
                          slot_name = "metadata", 
                          output_dir_path = output_dir_path,
                          feather_file_prefix = feather_file_prefix)
  
  # create feather file for assays (ADT, RNA count data, etc.)
  lapply(X = SeuratObject::Assays(object = seurat_object), 
         FUN = write_seurat_to_feather,
         seurat_object = seurat_object,
         slot_name = "assays",
         output_dir_path = output_dir_path,
         feather_file_prefix = feather_file_prefix)

  # create feather files for cell embeddings for reductions (e.g., PCA, UMAP, etc)
  lapply(X = SeuratObject::Reductions(object = seurat_object), 
         FUN = write_seurat_to_feather,
         seurat_object = seurat_object,
         slot_name = "reductions",
         output_dir_path = output_dir_path,
         feather_file_prefix = feather_file_prefix)
  
  #display a console message to the user that their files were successfully created
  message(paste0("Files successfully created in: ", output_dir_path))
  
  return(invisible(output_dir_path))
}
