#' Generate a Feather file from data in a Seurat object.
#'
#' This function retrieves data in specified slots ("metadata", "assays", or "reductions") from a user-inputted Seurat object and writes that data to a Feather file.
#' 
#' @param assay_or_reduction_name A string specifying the name of an assay (e.g., ADT, RNA, etc.) or reduction (e.g., PCA, UMAP, etc.) present in the Seurat object that is passed as a parameter to this function.
#' @param seurat_object A Seurat object containing metadata, assays, and reductions for a CITE-seq experiment.
#' @param slot_name A string specifying one of three possible values: "metadata", "assays", or "reductions".
#' @param feather_dir A string specifying the directory in which to store feather files generated by this function. Do not include slashes. Default value is a hidden folder named ".citeviz" in the current working directory.
#' @param feather_file_prefix A string specifying the prefix for each feather file generated from an input RDS file.
#'
#' @importFrom arrow write_feather
#' @importFrom SeuratObject GetAssayData Embeddings
#' @importFrom tibble rownames_to_column
#' 
#' @return The input feather directory (feather_dir), invisibly.
#' @export
#'
#' @examples \dontrun{
#' myso <- readRDS("path/to/RDS_file.rds")
#' write_seurat_to_feather(seurat_object = myso, slot_name = "metadata", feather_dir = ."citeviz", feather_file_prefix = "project123")
#' }
write_seurat_to_feather <- function(assay_or_reduction_name = NULL, seurat_object, slot_name, feather_dir = ".citeviz", feather_file_prefix = "sample"){
  if (slot_name == "metadata"){
    subdata_df <- as.data.frame(seurat_object[[]]) 
    output_file_identifier <- slot_name
  }
  else if (slot_name == "assays"){
    subdata_df <- as.data.frame(SeuratObject::GetAssayData(seurat_object, slot = "data", assay = assay_or_reduction_name)) 
    output_file_identifier <- assay_or_reduction_name
  }
  else if (slot_name == "reductions"){
    subdata_df <- as.data.frame(SeuratObject::Embeddings(seurat_object, reduction = assay_or_reduction_name)) 
    output_file_identifier <- assay_or_reduction_name
  }
  
  # convert rownames of dataframe to a column in the dataframe because for some reason, writing to a feather file doesn't preserve the original rowname data
  subdata_df <- subdata_df %>% tibble::rownames_to_column("column_of_rownames")
  
  #write extracted subdata to output file
  arrow::write_feather(x = subdata_df,
                       # generate platform-independent filepath
                       sink = file.path(feather_dir, 
                                        slot_name, 
                                        paste0(feather_file_prefix, "_", output_file_identifier, ".feather")))
  
  return(invisible(feather_dir))
}



#' Generate Feather files from data in a Seurat object.
#' 
#' This function is called before running the app so that the user's Seurat object can be converted into Feather files.
#'
#' @param seurat_object A Seurat object containing metadata, assays, and reductions for a CITE-seq experiment.
#' @param feather_dir A string specifying the directory in which to store feather files generated by this function. Do not include slashes. Default value is a hidden folder named ".citeviz" in the current working directory.
#' @param feather_file_prefix A string specifying the prefix for each feather file generated from an input RDS file.
#'
#' @importFrom SeuratObject Assays Reductions
#'
#' @return The input feather directory (feather_dir), invisibly.
#' @export
#'
#' @examples \dontrun{
#' myso <- readRDS("path/to/RDS_file.rds")
#' create_feather_files(seurat_object = myso, feather_dir = ".citeviz", feather_file_prefix = "project123")
#' }
create_feather_files <- function(seurat_object, feather_dir = ".citeviz", feather_file_prefix = "sample") {
  # generate a file prefix for the feather files to be generated, so that 
  # they don't overwrite existing feather files generated from other RDS files
  
  # if (is.null(feather_file_prefix)) {
  #   feather_file_prefix <- tools::file_path_sans_ext(basename(rds_filepath))
  # }
  
  # create feather file for metadata
  write_seurat_to_feather(seurat_object = seurat_object, 
                        slot_name = "metadata", 
                        feather_dir = feather_dir, 
                        feather_file_prefix = feather_file_prefix)
  
  # create feather file for assays (ADT, RNA count data, etc.)
  lapply(X = SeuratObject::Assays(object = seurat_object), 
         FUN = write_seurat_to_feather,
         seurat_object = seurat_object,
         slot_name = "assays",
         feather_dir = feather_dir,
         feather_file_prefix = feather_file_prefix)

  # create feather files for cell embeddings for reductions (e.g., PCA, UMAP, etc)
  lapply(X = SeuratObject::Reductions(object = seurat_object), 
         FUN = write_seurat_to_feather,
         seurat_object = seurat_object,
         slot_name = "reductions",
         feather_dir = feather_dir,
         feather_file_prefix = feather_file_prefix)
  
  #display a console message to the user that their files were successfully created
  message(paste0("Files successfully created in: ", feather_dir))
  
  return(invisible(feather_dir))
}
