#' Generate a Feather file from data in a Seurat object.
#'
#' This function retrieves data in specified slots ("metadata", "assays", or "reductions") from a user-inputted Seurat object and writes that data to a Feather file. The first column of data contains cell barcodes from a CITE-seq experiment, and subsequent columns contain metadata or count data for various assays (counts for each ADT, gene, etc.) and reductions (embeddings for UMAPs, PCAs, etc.). This columnar data storage format allows for much faster read access in downstream app processes.
#' 
#' @param assay_or_reduction_name A string specifying the name of an assay (e.g., ADT, RNA, etc.) or reduction (e.g., PCA, UMAP, etc.) present in the Seurat object that is passed as a parameter to this function.
#' @param seurat_object A Seurat object containing metadata, assays, and reductions for a CITE-seq experiment.
#' @param slot_name A string specifying one of three possible values: "metadata", "assays", or "reductions".
#' @param output_dir_path A string specifying the relative path to an output directory in which to store the Feather file generated by this function. Feather files generated from the same input Seurat object should be stored in the same directory. Path is relative to the current working directory.
#' @param feather_file_prefix A string specifying the prefix for each Feather file generated from an input Seurat object.
#'
#' @importFrom arrow write_feather
#' @importFrom SeuratObject GetAssayData Embeddings
#' @importFrom tibble rownames_to_column
#' 
#' @return The relative path to the feather file that was generated. This value is returned invisibly.
#' @export
#'
#' @examples \dontrun{
#' myso <- readRDS("path/to/RDS_file.rds")
#' write_seurat_to_feather(seurat_object = myso, slot_name = "metadata", feather_parent_dir = "citeviz_arrow", feather_file_prefix = "project123")
#' }
write_seurat_to_feather <- function(assay_or_reduction_name = NULL, seurat_object, slot_name, output_dir_path, feather_file_prefix){
  # initialize output_file_identifier to empty string by default
  output_file_identifier <- ""
  
  if (slot_name == "metadata"){
    subdata_df <- as.data.frame(seurat_object[[]]) 
  }
  if (slot_name == "assays"){
    # transpose assay data so that that rownames are cell barcodes and column names are ADTs/Genes/etc.
    # convert transposed output matrix into data frame again
    subdata_df <- as.data.frame(t(
        as.data.frame(SeuratObject::GetAssayData(object = seurat_object, 
                                                 slot = "data", 
                                                 assay = assay_or_reduction_name))
      ))
    output_file_identifier <- paste0("_", assay_or_reduction_name)
  }
  else if (slot_name == "reductions"){
    subdata_df <- as.data.frame(
      SeuratObject::Embeddings(object = seurat_object, 
                               reduction = assay_or_reduction_name)) 
    output_file_identifier <- paste0("_", assay_or_reduction_name)
  }
  
  # convert rownames of dataframe to a column in the dataframe because writing to a feather file doesn't preserve the original rowname data
  subdata_df <- tibble::rownames_to_column(subdata_df, "cell_barcodes")
  
  # generate platform-independent output file path
  output_filepath <- file.path(output_dir_path,
                               paste0(feather_file_prefix, "_", slot_name, output_file_identifier, ".feather"))
  
  # check if output directory exists in user's filesystem. If not, create the necessary folders in the path
  if (!dir.exists(output_dir_path)) {
    dir.create(output_dir_path)
  }
  
  # write extracted subdata to output file
  arrow::write_feather(x = subdata_df, sink = output_filepath)
  
  return(invisible(output_filepath))
}


#' Generate Feather files from data in a Seurat object.
#' 
#' This function is called before running the app so that the user's Seurat object can be converted into Feather files.
#'
#' @param seurat_object A Seurat object containing metadata, assays, and reductions for a CITE-seq experiment.
#' @param feather_parent_dir A string specifying the directory in which all project-specific Feather folders/files are stored for this app. Do not include slashes. Default value is a folder named "citeviz_arrow" in the current working directory.
#' @param feather_file_prefix A string specifying the prefix for each feather file generated from an input Seurat object. These Feather files will be stored in a sub-directory named with the same prefix, and this subfolder can be found within the feather parent directory. It is recommended to set the feather file prefix to be the same as the base filename of the original RDS file the Seurat object originated from (i.e., if the input Seurat object came from an RDS file called "my_project_data.rds", then the prefix for the arrow files should be "my_project_data".) 
#'
#' @importFrom SeuratObject Assays Reductions
#'
#' @return The path to the sub-directory (in the format "feather_parent_dir/feather_file_prefix") where Feather files generated from the same input Seurat object are stored. This path is relative to the user's current working directory. This value is returned invisibly.
#' @export
#'
#' @examples \dontrun{
#' myso <- readRDS("path/to/RDS_file.rds")
#' create_feather_files(seurat_object = myso, feather_parent_dir = "citeviz_arrow", feather_file_prefix = "project123")
#' }
create_feather_files <- function(seurat_object, feather_parent_dir = "citeviz_arrow", feather_file_prefix = "project1") {
  # generate a file prefix for the feather files to be generated, so that 
  # they don't overwrite existing feather files generated from other RDS files
  # if (is.null(feather_file_prefix)) {
  #   feather_file_prefix <- tools::file_path_sans_ext(basename(rds_filepath))
  # }
  
  # generate platform-independent output folder path
  output_dir_path <- file.path(feather_parent_dir, feather_file_prefix)
  
  # create feather file for metadata
  write_seurat_to_feather(seurat_object = seurat_object, 
                          slot_name = "metadata", 
                          output_dir_path = output_dir_path,
                          feather_file_prefix = feather_file_prefix)
  
  # create feather file for assays (ADT, RNA count data, etc.)
  lapply(X = SeuratObject::Assays(object = seurat_object), 
         FUN = write_seurat_to_feather,
         seurat_object = seurat_object,
         slot_name = "assays",
         output_dir_path = output_dir_path,
         feather_file_prefix = feather_file_prefix)

  # create feather files for cell embeddings for reductions (e.g., PCA, UMAP, etc)
  lapply(X = SeuratObject::Reductions(object = seurat_object), 
         FUN = write_seurat_to_feather,
         seurat_object = seurat_object,
         slot_name = "reductions",
         output_dir_path = output_dir_path,
         feather_file_prefix = feather_file_prefix)
  
  #display a console message to the user that their files were successfully created
  message(paste0("Files successfully created in: ", output_dir_path))
  
  return(invisible(output_dir_path))
}


#' Find which alternate experiment within a SingleCellExperiment object a given reduction can be found in. This is needed if a user wants to retrieve and plot the cell embeddings for a given reduction from a SingleCellExperiment object.
#'
#' @param alt_exp_name A string specifying the name of an alternate experiment from a SingleCellExperiment object in which to search if a given reduction is present. The names of alternate experiments can be obtained by looking through SingleCellExperiment::altExpNames(x), where x is a SingleCellExperiment object.
#' @param sce_object A SingleCellExperiment object containing data from a CITE-seq experiment processed with Seurat.
#' @param reduction_name A string specifying the name of a reduction (e.g., "UMAP", "PCA", etc.).
#'
#' @importFrom SingleCellExperiment altExp reducedDimNames
#'
#' @return A string specifying the name of an alternate experiment (e.g., "ADT", "RNA", "SCT", etc.) in which the cell embeddings for a given reduction can be found.
#' @export
#'
#' @examples \dontrun{
#' sce_object <- readRDS("path/to/RDS_file_containing_SCE_object.rds")
#' alt_exp_name <- SingleCellExperiment::altExpNames(sce_object)[1]
#' reduction_name <- "UMAP"
#' alt_exp_of_desired_reduction <- find_reduction_in_altSCE(alt_exp_name, sce_object, reduction_name)
#' }
find_reduction_in_altSCE <- function(alt_exp_name, sce_object, reduction_name) {
  alt_exp_object <- SingleCellExperiment::altExp(x = sce_object, 
                                                 e = alt_exp_name)
  alt_exp_reductions <- SingleCellExperiment::reducedDimNames(alt_exp_object)
  # match the reduction name exactly when searching if it's within a list
  reduction_finder_results <- grepl(paste0("^", reduction_name, "$"), 
                                    alt_exp_reductions)
  if (TRUE %in% reduction_finder_results) {
    return(alt_exp_name)
  }
}


#' Get dropdown menu options for selectInput elements in CITEViz.
#' 
#' This function retrieves various categories of data (e.g., metadata, reductions, or assays) from user-uploaded input file(s) (e.g., an RDS file containing a Seurat object or Feather files) and returns a character vector of items with which to populate a dropdown menu in the CITEViz user interface. This function can also get subchoices for a dropdown menu after a user has selected an assay they want to view. For example, if a user selects the "ADT" assay, then this function will return a vector of all the possible ADTs a user can choose to view from their input data. If a user selects the "RNA" assay, then this function will return a vector of all the genes a user can choose to view from their input data.
#'
#' @param category A string specifying the category of data to retrieve. Categories are based on slots in a Seurat object produced from a CITE-seq experiment Possible values are "metadata", "reductions", or "assays".
#' @param input_data_type An integer value indicating if the user-uploaded input files are RDS files holding Seurat objects or SingleCellExperiment objects, or Feather/Arrow files (1 = Seurat object, 2 = SingleCellExperiment object, 3 = Feather/Arrow file, etc.)
#' @param rds_object An RDS object containing metadata, assays, and reductions for a CITE-seq experiment. Can be NULL if the user uploaded Feather/Arrow files instead of an RDS file.
#' @param arrow_file_list A vector containing a list of Feather/Arrow files generated by CITEViz::create_feather_files() and uploaded by the user in the CITEViz UI. Can be NULL if the user uploaded an RDS file instead of Feather/Arrow files.
#' @param input_file_df A dataframe generated by retrieving file input data from a fileInput element in the UI (i.e., by running input$file_input in the app server). This dataframe contains information about each file uploaded by the user, such as the name of each file as it appears on the user's local filesystem (input_file_df$name) and the temporary datapath with which data from the file can be read in (input_file_df$datapath).
#' @param assay_name A string specifying the name of an assay (e.g., "ADT", "RNA", etc.) from a Seurat-processed CITE-seq experiment.
#' 
#' @import magrittr
#' @importFrom SeuratObject Assays Reductions GetAssayData
#' @importFrom arrow read_feather
#' @importFrom dplyr select
#' @importFrom tools file_path_sans_ext
#' @importFrom SingleCellExperiment altExp altExpNames colData mainExpName reducedDimNames
#'
#' @return A character vector of items with which to populate a dropdown menu in the CITEViz UI, sorted in ascending order.
#' @export
#'
#' @examples \dontrun{
#' # if RDS file is uploaded by user
#' myso <- readRDS("path/to/RDS_file.rds")
#' input_file_data <- input$file_input
#' get_choices("metadata", input_data_type = FALSE, rds_object = myso, arrow_file_list = NULL, input_file_df = input_file_data, assay_name = NULL)
#' 
#' # if Feather/Arrow files are uploaded by user
#' input_file_data <- input$file_input
#' arrow_filenames <- input_file_data$name
#' get_choices("metadata", input_data_type = TRUE, rds_object = NULL, arrow_file_list = arrow_filenames, input_file_df = input_file_data, assay_name = NULL)
#' }
#' 
get_choices <- function(category, input_data_type, rds_object, arrow_file_list, input_file_df, assay_name = NULL) {
  menu_choices <- NULL
  # if input data type is a Seurat object from an RDS file
  if (input_data_type == 1  & !is.null(rds_object)) {
    if (is.null(category) & !is.null(assay_name)) {
      menu_choices <- rownames(SeuratObject::GetAssayData(object = rds_object, 
                                                          slot = "data",
                                                          assay = assay_name))
    }
    else if (category == "metadata") {
      menu_choices <- rds_object[[]] %>%
        dplyr::select(where(is.factor) | where(is.character)) %>% 
        colnames()
    }
    else if (category == "reductions") {
      menu_choices <- SeuratObject::Reductions(rds_object)
    }
    else if (category == "assays") {
      menu_choices <- SeuratObject::Assays(object = rds_object)
    }
  }
  
  # if input data type is a SingleCellExperiment object from an RDS file
  else if (input_data_type == 2  & !is.null(rds_object)) {
    if (is.null(category) & !is.null(assay_name)) {
      if (SingleCellExperiment::mainExpName(rds_object) == assay_name) {
        menu_choices <- rownames(rds_object)
      }
      else {
        menu_choices <- rownames(SingleCellExperiment::altExp(x = rds_object,
                                                              e = assay_name))
      }
    }
    else if (category == "metadata") {
      menu_choices <- as.data.frame(SingleCellExperiment::colData(rds_object)) %>% 
        dplyr::select(where(is.factor) | where(is.character)) %>%
        colnames()
    }
    else if (category == "reductions") {
      menu_choices <- unlist(SingleCellExperiment::applySCE(rds_object, 
                                                            reducedDimNames))
    }
    else if (category == "assays") {
      menu_choices <- c(SingleCellExperiment::mainExpName(rds_object), 
                        SingleCellExperiment::altExpNames(rds_object))
    }
  }
  
  # if input data type is data from Arrow/Feather files
  else if (input_data_type == 3 & !is.null(arrow_file_list)) {
    if (is.null(category) & !is.null(assay_name)) {
      assay_file_index <- grep(pattern = paste0("assays_", assay_name),
                             x = arrow_file_list,
                             ignore.case = TRUE, value = FALSE)
      assay_filepath <- input_file_df$datapath[assay_file_index]
      menu_choices <- arrow::read_feather(assay_filepath) %>%
        dplyr::select(!cell_barcodes) %>%
        colnames()
    }
    else {
      file_indexes <- grep(pattern = category,
                           x = arrow_file_list,
                           ignore.case = TRUE, value = FALSE)
      if (category == "metadata") {
        filepath <- input_file_df$datapath[file_indexes]
        menu_choices <- arrow::read_feather(filepath) %>% # get columns that contain factors or characters
          dplyr::select(!cell_barcodes & (where(is.factor) | where(is.character))) %>%
          colnames()
      }
      # from arrow file list, split filenames so that only each reduction or assay option is left in the vector
      # populate dropdown menu with this vector of reductions or assays
      else if (category == "reductions" | category == "assays") {
        filenames <- input_file_df$name[file_indexes]
        menu_choices <- tools::file_path_sans_ext(filenames) %>%
          strsplit(split = paste0("_", category, "_")) %>%
          lapply(tail, n = 1) %>%
          unlist()
      }
    }
  }
  return(sort(as.vector(menu_choices)))
}


#' Title
#'
#' @param category A string specifying the category of data to retrieve. Categories are based on slots in a Seurat object produced from a CITE-seq experiment Possible values are "metadata", "reductions", or "assays".
#' @param input_data_type An integer value indicating if the user-uploaded input files are RDS files holding Seurat objects or SingleCellExperiment objects, or Feather/Arrow files (1 = Seurat object, 2 = SingleCellExperiment object, 3 = Feather/Arrow file, etc.)
#' @param rds_object An RDS object containing metadata, assays, and reductions for a CITE-seq experiment. Can be NULL if the user uploaded Feather/Arrow files instead of an RDS file.
#' @param arrow_file_list A vector containing a list of Feather/Arrow files generated by CITEViz::create_feather_files() and uploaded by the user in the CITEViz UI. Can be NULL if the user uploaded an RDS file instead of Feather/Arrow files.
#' @param input_file_df A dataframe generated by retrieving file input data from a fileInput element in the UI (i.e., by running input$file_input in the app server). This dataframe contains information about each file uploaded by the user, such as the name of each file as it appears on the user's local filesystem (input_file_df$name) and the temporary datapath with which data from the file can be read in (input_file_df$datapath).
#' @param assay_name A string specifying the name of an assay (e.g., "ADT", "RNA", etc.) from a Seurat-processed CITE-seq experiment. Can be NULL if not retrieving any assay data.
#' @param reduction_name A string specifying the name of an reduction (e.g., "pca", "umap", etc.) from a Seurat-processed CITE-seq experiment. Can be NULL if not retrieving any reduction data.
#' @param assay_data_to_get Character vector specifying the column(s) from assay data to get (i.e. if the assay is "ADT", then a possible value for assay_data_to_get may be c("ab-CD10", "ab-CD38")). Can be NULL if not retrieving any assay data.
#' 
#' @import magrittr
#' @importFrom SeuratObject GetAssayData Embeddings
#' @importFrom arrow read_feather
#' @importFrom tibble column_to_rownames
#' @importFrom SingleCellExperiment altExp colData logcounts mainExpName reducedDimNames reducedDim
#' 
#' @return A dataframe containing metadata, assay count data, or reduction embeddings data that was generated in a Seurat-processed CITE-seq experiment. The rownames of the dataframe are cell barcodes, and the column names are metadata columns, assay columns (i.e. if assay is "RNA", then assay columns would be genes), or reduction embedding columns (i.e. if the reduction is "pca", the embedding data colummns would be PC1, PC2, etc).
#' @export
#'
#' @examples \dontrun{
#' # if RDS file is uploaded by user
#' myso <- readRDS("path/to/RDS_file.rds")
#' input_file_data <- input$file_input
#' get_data("reductions", input_data_type = FALSE, rds_object = myso, arrow_file_list = NULL, input_file_df = input_file_data, reduction_name = "pca")
#' 
#' # if Feather/Arrow files are uploaded by user
#' input_file_data <- input$file_input
#' arrow_filenames <- input_file_data$name
#' get_data("reductions", input_data_type = TRUE, rds_object = NULL, arrow_file_list = arrow_filenames, input_file_df = input_file_data, reduction_name = "pca")
#' }
#' 
get_data <- function(category, input_data_type, rds_object, arrow_file_list, input_file_df, assay_name = NULL, reduction_name = NULL, assay_data_to_get = NULL) {
  data <- NULL
  # if input data type is a Seurat object from an RDS file
  if (input_data_type == 1 & !is.null(rds_object)) {
    if (category == "metadata") {
      # get all metadata in seurat object
      data <- rds_object[[]]
    }
    else if (category == "assays" & !is.null(assay_name)) {
      # get count data from seurat object for a given assay (ADT, RNA, etc) 
      # and transpose it so that colnames are RNAs/ADTs/etc and rownames are cell barcodes, 
      # for consistency with the way assay data is stored/accessed in arrow/feather files
      data <- t(as.data.frame(
        SeuratObject::GetAssayData(object = rds_object, 
                                   slot = "data",
                                   assay = assay_name))[assay_data_to_get, ])
    }
    else if (category == "reductions" & !is.null(reduction_name)) {
      # we need, at most, 3 reduction dimensions for plotting, so don't get more than 3 dimensions
      # if a reduction doesn't have 3 dimensions (i.e. if PCA data only contains PC1 and PC2),
      # then just get whatever is there
      num_components <- ncol(SeuratObject::Embeddings(object = rds_object, 
                                                      reduction = reduction_name))
      if (num_components < 3) {
        data <- SeuratObject::Embeddings(object = rds_object, 
                                         reduction = reduction_name)
      }
      else {
        data <- SeuratObject::Embeddings(object = rds_object, 
                                         reduction = reduction_name)[, 1:3]
      }
    }
  }
  
  # if input data type is a SingleCellExperiment object from an RDS file
  else if (input_data_type == 2  & !is.null(rds_object)) {
    if (category == "metadata") {
      data <- SingleCellExperiment::colData(rds_object)
    }
    else if (category == "assays" & !is.null(assay_name)) {
      if (SingleCellExperiment::mainExpName(rds_object) == assay_name) {
        data <- t(as.matrix(SingleCellExperiment::logcounts(rds_object)))
      }
      else {
        alt_exp_obj <- SingleCellExperiment::altExp(x = rds_object, 
                                                    e = assay_name)
        data <- t(as.matrix(SingleCellExperiment::logcounts(alt_exp_obj)))
      }
    }
    else if (category == "reductions" & !is.null(reduction_name)) {
      main_exp_reductions <- SingleCellExperiment::reducedDimNames(rds_object)
      # match the reduction name exactly when searching if it's within a list
      reduction_finder_results <- grepl(pattern = paste0("^", reduction_name, "$"), 
                             x = main_exp_reductions)
      if (TRUE %in% reduction_finder_results) {
        all_data <- SingleCellExperiment::reducedDim(rds_object, 
                                                     type = reduction_name, 
                                                     withDimnames = FALSE)
      }
      else {
        # find which alternate experiment a reduction can be found under
        alt_exp_names_list <- SingleCellExperiment::altExpNames(rds_object)
        assay_name <- lapply(alt_exp_names_list, 
                             FUN = find_reduction_in_altSCE, 
                             sce_object = rds_object, 
                             reduction_name = reduction_name) %>% unlist()
        alt_exp_obj <- SingleCellExperiment::altExp(x = rds_object,
                                                    e = assay_name)
        all_data <- SingleCellExperiment::reducedDim(alt_exp_obj,
                                                     type = reduction_name, 
                                                     withDimnames = FALSE)
      }
      num_components <- ncol(all_data)
      if (num_components < 3) {
        data <- all_data
      }
      else {
        data <- all_data[, 1:3]
      }
    }
  }
  
  # if input data type is data from Arrow/Feather files
  else if (input_data_type == 3 & !is.null(arrow_file_list)) {
    if (category == "metadata") {
      file_index <- grep(pattern = category,
                         x = arrow_file_list,
                         ignore.case = TRUE, value = FALSE)
      filepath <- input_file_df$datapath[file_index]
      data <- arrow::read_feather(filepath) %>%
        tibble::column_to_rownames(var = "cell_barcodes")
    }
    else if (category == "assays" & !is.null(assay_name)) {
      file_index <- grep(pattern = paste0("assays_", assay_name),
                         x = arrow_file_list,
                         ignore.case = TRUE, value = FALSE)
      filepath <- input_file_df$datapath[file_index]
      data <- arrow::read_feather(filepath,
                                  col_select = c("cell_barcodes", assay_data_to_get)) %>%
        tibble::column_to_rownames(var = "cell_barcodes")
    }
    else if (category == "reductions" & !is.null(reduction_name)) {
      file_index <- grep(pattern = paste0("reductions_", reduction_name),
                         x = arrow_file_list,
                         ignore.case = TRUE, value = FALSE)
      filepath <- input_file_df$datapath[file_index]
      
      # Note that 1st column in feather file for reductions is the cell_barcode column, 
      # so ncol()-1 is the number of reduction dimensions present in the data
      num_components <- ncol(arrow::read_feather(filepath)) - 1
      if (num_components < 3) {
        data <- arrow::read_feather(filepath) %>%
          tibble::column_to_rownames(var = "cell_barcodes")
      }
      else {
        data <- arrow::read_feather(filepath, col_select = 1:4) %>%
          tibble::column_to_rownames(var = "cell_barcodes")
      }
    }
  }
  return(as.data.frame(data))
}

